In [1]:
# importing necessary libraries

import pandas as pd
import numpy as np

In [2]:
# loading dataset and assgning it to a variable called df

df=pd.read_csv("viral_shorts_reels_performance_dataset.csv")
df

,video_id,duration_sec,hook_strength_score,niche,views_first_hour,views_total,retention_rate,first_3_sec_engagement,music_type,upload_time
0,vid_1,16,0.61,Motivation,10695,886048,0.85,0.26,Viral Track,2024-02-09
1,vid_2,19,0.34,Tech,1812,198243,0.56,0.80,Trending,2024-04-17
2,vid_3,13,0.47,Travel,23247,584171,0.14,0.27,Trending,2024-01-01
3,vid_4,36,0.21,Travel,11515,491291,0.29,0.81,Remix,2024-04-01
4,vid_5,8,0.75,Gaming,13474,607425,0.27,0.44,Viral Track,2024-01-15
...,...,...,...,...,...,...,...,...,...,...
395,vid_396,21,0.26,Gaming,25585,641343,0.95,0.97,No Music,2024-09-26
396,vid_397,34,0.74,Food,17315,556771,0.57,0.87,Original,2024-11-06
397,vid_398,32,0.52,Beauty,38460,929848,0.29,0.56,Original,2024-06-12
398,vid_399,43,0.44,Motivation,28205,528558,0.79,0.26,Viral Track,2024-05-04
399,vid_400,17,0.52,Education,22502,491407,0.86,0.92,Viral Track,2024-10-07

In [3]:
# To check the count   of rows and columns

df.shape

(400, 10)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                400 non-null    object
 1   duration_sec            400 non-null    int64
 2   hook_strength_score     400 non-null    float64
 3   niche                   400 non-null    object
 4   views_first_hour        400 non-null    int64
 5   views_total             400 non-null    int64
 6   retention_rate          400 non-null    float64
 7   first_3_sec_engagement  400 non-null    float64
 8   music_type              400 non-null    object
 9   upload_time             400 non-null    object
dtypes: float64(3), int64(3), object(4)
memory usage: 31.4+ KB

In [9]:
# checking for null values

df.isnull().sum()

video_id                  0
duration_sec              0
hook_strength_score       0
niche                     0
views_first_hour          0
views_total               0
retention_rate            0
first_3_sec_engagement    0
music_type                0
upload_time               0
dtype: int64

In [11]:
df.describe()

,duration_sec,hook_strength_score,views_first_hour,views_total,retention_rate,first_3_sec_engagement
count,400.000000,400.000000,400.00000,400.000000,400.000000,400.000000
mean,25.085000,0.584850,24730.51000,486338.497500,0.528275,0.617800
std,11.649552,0.229429,14180.99207,291672.505188,0.245214,0.230906
min,5.000000,0.200000,84.00000,1924.000000,0.100000,0.200000
25%,15.000000,0.390000,12497.00000,227904.500000,0.310000,0.420000
50%,26.000000,0.590000,24984.00000,473516.000000,0.530000,0.635000
75%,35.000000,0.770000,36222.25000,745058.750000,0.740000,0.820000
max,44.000000,1.000000,49812.00000,992963.000000,0.950000,0.990000

In [13]:
df.head()

,video_id,duration_sec,hook_strength_score,niche,views_first_hour,views_total,retention_rate,first_3_sec_engagement,music_type,upload_time
0,vid_1,16,0.61,Motivation,10695,886048,0.85,0.26,Viral Track,2024-02-09
1,vid_2,19,0.34,Tech,1812,198243,0.56,0.80,Trending,2024-04-17
2,vid_3,13,0.47,Travel,23247,584171,0.14,0.27,Trending,2024-01-01
3,vid_4,36,0.21,Travel,11515,491291,0.29,0.81,Remix,2024-04-01
4,vid_5,8,0.75,Gaming,13474,607425,0.27,0.44,Viral Track,2024-01-15

In [15]:
# Made a new Column Duration categories as short medium and long to categorize video durations 

df['duration_categories']=pd.qcut(df['duration_sec'],q=3,labels=['short','medium','long'])
df[['duration_categories','duration_sec']]

    duration_categories  duration_sec
0                 short            16
1                 short            19
2                 short            13
3                  long            36
4                 short             8
..                  ...           ...
395              medium            21
396                long            34
397              medium            32
398                long            43
399               short            17

[400 rows x 2 columns]

In [17]:
df.head()

,video_id,duration_sec,hook_strength_score,niche,views_first_hour,views_total,retention_rate,first_3_sec_engagement,music_type,upload_time,duration_categories
0,vid_1,16,0.61,Motivation,10695,886048,0.85,0.26,Viral Track,2024-02-09,short
1,vid_2,19,0.34,Tech,1812,198243,0.56,0.80,Trending,2024-04-17,short
2,vid_3,13,0.47,Travel,23247,584171,0.14,0.27,Trending,2024-01-01,short
3,vid_4,36,0.21,Travel,11515,491291,0.29,0.81,Remix,2024-04-01,long
4,vid_5,8,0.75,Gaming,13474,607425,0.27,0.44,Viral Track,2024-01-15,short

In [19]:
#made a growth percentage column to calculate growth percentage

df['growth_percentage']=df['views_first_hour']/df['views_total']*100
df.head()

,video_id,duration_sec,hook_strength_score,niche,views_first_hour,views_total,retention_rate,first_3_sec_engagement,music_type,upload_time,duration_categories,growth_percentage
0,vid_1,16,0.61,Motivation,10695,886048,0.85,0.26,Viral Track,2024-02-09,short,1.207045
1,vid_2,19,0.34,Tech,1812,198243,0.56,0.80,Trending,2024-04-17,short,0.914030
2,vid_3,13,0.47,Travel,23247,584171,0.14,0.27,Trending,2024-01-01,short,3.979485
3,vid_4,36,0.21,Travel,11515,491291,0.29,0.81,Remix,2024-04-01,long,2.343825
4,vid_5,8,0.75,Gaming,13474,607425,0.27,0.44,Viral Track,2024-01-15,short,2.218216

In [23]:
df.dtypes

video_id                    object
duration_sec                 int64
hook_strength_score        float64
niche                       object
views_first_hour             int64
views_total                  int64
retention_rate             float64
first_3_sec_engagement     float64
music_type                  object
upload_time                 object
duration_categories       category
growth_percentage          float64
dtype: object

In [25]:
# Some rows exceeded the bracket of 100 percent clearly it had a data entry fault

df[df['growth_percentage']>100].sort_values(by='growth_percentage',ascending=False)

,video_id,duration_sec,hook_strength_score,niche,views_first_hour,views_total,retention_rate,first_3_sec_engagement,music_type,upload_time,duration_categories,growth_percentage
115,vid_116,8,0.99,Fitness,17084,1924,0.83,0.80,No Music,2024-10-05,short,887.941788
98,vid_99,19,0.94,Music,31891,5716,0.45,0.60,Original,2024-11-17,short,557.925122
276,vid_277,25,0.75,Fitness,23725,5901,0.62,0.32,Viral Track,2024-01-18,medium,402.050500
77,vid_78,8,0.72,Tech,39685,10420,0.85,0.73,Trending,2024-02-10,short,380.854127
253,vid_254,43,0.55,Beauty,23378,8162,0.71,0.32,Viral Track,2024-06-28,long,286.424896
270,vid_271,29,0.43,Tech,26423,10666,0.25,0.30,Original,2024-01-02,medium,247.731108
228,vid_229,21,0.42,Travel,27246,12678,0.49,0.51,Viral Track,2024-07-11,medium,214.907714
14,vid_15,38,0.81,Fitness,38655,18647,0.46,0.83,No Music,2024-10-17,long,207.298761
216,vid_217,9,0.24,Gaming,42026,24126,0.71,0.94,No Music,2024-07-27,short,174.193816
278,vid_279,31,0.51,Music,25462,22034,0.14,0.93,Viral Track,2024-05-25,medium,115.557774
309,vid_310,44,0.24,Gaming,37944,35895,0.81,0.49,Remix,2024-11-16,long,105.708316

In [27]:
# swapped values which exceeded higher percentage considering it as a data entry mistake 
a=df['growth_percentage'] > 100
df.loc[a, ['views_first_hour', 'views_total']] = (df.loc[a, ['views_total', 'views_first_hour']].values)

In [29]:
# recalculating growth percentage
df['growth_percentage']=df['views_first_hour']/df['views_total']*100

In [31]:
# re-checking for values exceeding 100

df[df['growth_percentage']>100]

Empty DataFrame
Columns: [video_id, duration_sec, hook_strength_score, niche, views_first_hour, views_total, retention_rate, first_3_sec_engagement, music_type, upload_time, duration_categories, growth_percentage]
Index: []

In [33]:
df[['views_total', 'views_first_hour','growth_percentage']].reset_index().sort_values(by='growth_percentage',ascending=False)

     index  views_total  views_first_hour  growth_percentage
309    309        37944             35895          94.599937
36      36         6860              6483          94.504373
278    278        25462             22034          86.536800
112    112        40037             31761          79.329121
356    356        35583             27655          77.719698
..     ...          ...               ...                ...
20      20       979910              2974           0.303497
239    239       695646              1733           0.249121
281    281       184517               386           0.209195
162    162       611707               410           0.067026
379    379       470542                84           0.017852

[400 rows x 4 columns]

In [35]:
# made a new column for better categorization of growth 

df['growth_category']=pd.qcut(df['growth_percentage'],q=4,labels=['late_viral','balanced_growth','early_growth','Flash_viral'])

In [37]:
df[['growth_percentage','growth_category']].head()

   growth_percentage  growth_category
0           1.207045       late_viral
1           0.914030       late_viral
2           3.979485  balanced_growth
3           2.343825       late_viral
4           2.218216       late_viral

In [39]:
df['growth_category_description']=df['growth_category'].map(
    {'late_viral':'Not strong initially goes viral later',
     'balanced_growth':'performs consistently over time',
     'early_growth':'good start moderate traction',
    'Flash_viral':'strong first hour then gradually declines'}
)

In [41]:
df[['growth_percentage','growth_category','growth_category_description']].sort_values(by='growth_percentage',ascending=False).head()

,growth_percentage,growth_category,growth_category_description
309,94.599937,Flash_viral,strong first hour then gradually declines
36,94.504373,Flash_viral,strong first hour then gradually declines
278,86.536800,Flash_viral,strong first hour then gradually declines
112,79.329121,Flash_viral,strong first hour then gradually declines
356,77.719698,Flash_viral,strong first hour then gradually declines

# Connecting to MySQl for deeper analysis

In [44]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\hp\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\hp\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\hp\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Note: you may need to restart the kernel to use updated packages.

In [45]:
from sqlalchemy import create_engine

# MySQL connection
username = "root"
password = "admin"
host = "localhost"
port = "3306"
database = "viral_reels"

engine = create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

# Write DataFrame to MySQL
table_name = "reels_analysis"   
df.to_sql(table_name, engine, if_exists="replace", index=False)

# Read back sample
pd.read_sql("SELECT * FROM reels_analysis LIMIT 5;", engine)

,video_id,duration_sec,hook_strength_score,niche,views_first_hour,views_total,retention_rate,first_3_sec_engagement,music_type,upload_time,duration_categories,growth_percentage,growth_category,growth_category_description
0,vid_1,16,0.61,Motivation,10695,886048,0.85,0.26,Viral Track,2024-02-09,short,1.207045,late_viral,Not strong initially goes viral later
1,vid_2,19,0.34,Tech,1812,198243,0.56,0.80,Trending,2024-04-17,short,0.914030,late_viral,Not strong initially goes viral later
2,vid_3,13,0.47,Travel,23247,584171,0.14,0.27,Trending,2024-01-01,short,3.979485,balanced_growth,performs consistently over time
3,vid_4,36,0.21,Travel,11515,491291,0.29,0.81,Remix,2024-04-01,long,2.343825,late_viral,Not strong initially goes viral later
4,vid_5,8,0.75,Gaming,13474,607425,0.27,0.44,Viral Track,2024-01-15,short,2.218216,late_viral,Not strong initially goes viral later